server:
  port: 8088
  body_limit: 1048576 # 1MB
  allowed_origins:
    - "http://127.0.0.1:5173"
    - "http://127.0.0.1:5174"
    - "http://127.0.0.1:5175"
    - "http://localhost:5173"
    - "http://localhost:5174"
    - "http://localhost:5175"

log:
  dir: ./logs
  max_size: 104857600
  file_prefix: sentry
  rotate_daily: true

sourcemap:
  enabled: true
  dir: ../client/dist/.sourcemaps
